repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=2024"]
        exclude: ^results/.*\.gif$
      - id: check-docstring-first

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: env UV_CACHE_DIR=.uv_cache uv run --no-sync ruff check --fix --show-fixes
        language: system
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        name: ruff format
        entry: env UV_CACHE_DIR=.uv_cache uv run --no-sync ruff format
        language: system
        types_or: [python, pyi, jupyter]
      - id: ty-check
        name: ty check
        entry: env UV_CACHE_DIR=.uv_cache uv run --no-sync ty check
        language: system
        pass_filenames: false
        always_run: true
