views:
  - name: "Camera&Map"
    type: "Container"
    layout: "Horizontal"
    views:
      - name: "Local Map"
        type: "Spatial3D"
        origin: "/world/estimates/local_map"
        streams:
          - id: "pnp_pose"
            module: "dynamic_transform"
            branch: "frontend_frame"
            entity: "world/estimates/local_map/pnp/base_link"
            options:
              show_axes: true
          - id: "cam0_in_body"
            module: "static_transform"
            branch: "frontend_frame"
            entity: "world/estimates/local_map/pnp/base_link/cam0"
            options:
              show_axes: true
          - id: "points"
            module: "pointcloud"
            branch: "frontend_frame"
            entity: "world/estimates/local_map/pnp/base_link/cam0/landmarks"
            options:
              points_size_prop_name: points_size
          - id: "initialized_landmarks"
            module: "pointcloud"
            branch: "frontend_frame"
            entity: "world/estimates/local_map/pnp/base_link/cam0/ray_landmarks"
            options:
              points_size_prop_name: initialized_landmarks_size
              default_color: [255, 80, 220]
              visualize_covariance: true
              covariance_color: [255, 160, 80]
          - id: "local_map_points"
            module: "pointcloud"
            branch: "frontend_frame"
            entity: "world/estimates/local_map/map/landmarks"
            options:
              points_size_prop_name: local_map_points_size
              visualize_covariance: true
              covariance_color: [80, 220, 255]
          - id: "optimized_pose"
            module: "dynamic_transform"
            branch: "fixedlag_frame"
            entity: "world/estimates/local_map/factor_graph/base_link"
            options:
              show_axes: true
          - id: "cam0_in_body"
            module: "static_transform"
            branch: "fixedlag_frame"
            entity: "world/estimates/local_map/factor_graph/base_link/cam0"
            options:
              show_axes: true
          - id: "optimized_points"
            module: "pointcloud"
            branch: "fixedlag_frame"
            entity: "world/estimates/local_map/factor_graph/map/landmarks"
            options:
              points_size_prop_name: optimized_points_size
      - name: "Rectified Left Image"
        type: "Spatial2D"
        branch: "frontend_frame"
        origin: "/sensors/cam0/rect/image"
        streams:
          - id: "left_rect"
            module: "image"
            entity: "."
            options:
              width_field: "width"
              height_field: "height"
          - id: "active_feat"
            module: "features"
            entity: "/sensors/cam0/rect/image/features"
