views:
  - name: "Front-End Metrics"
    type: "Container"
    layout: "Horizontal"
    branch: "frontend_frame"
    views:
      - name: "Keyframe Selector Metrics"
        type: "Container"
        layout: "Vertical"
        views:
          - name: "keyframe_dt"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_dt"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_dt/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff"
                  label: "keyframe_time_diff"
                  width: 2.0
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_dt/min_threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff_min_threshold"
                  label: "min_threshold"
                  color: [255, 0, 0]
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "metrics/keyframe_selector/keyframe_dt/max_threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff_max_threshold"
                  label: "max_threshold"
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false

          - name: "keyframe_connectivity"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_connectivity"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_connectivity/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_connectivity_ratio"
                  label: "keyframe_connectivity"
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_connectivity/threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_connectivity_ratio_threshold"
                  label: "threshold"
                  width: 1.0
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false

          - name: "keyframe_parallax"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_parallax"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_parallax/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_median_parallax"
                  label: "keyframe_parallax"
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_parallax/threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_median_parallax_threshold"
                  label: "threshold"
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false
      - name: "Feature Tracker Metrics"
        type: "Container"
        layout: "Vertical"
        views:
          - name: "Features Count"
            type: "TimeSeries"
            origin: "/metrics/tracker/features_count"
            streams:
              - id: "all_features_count"
                module: "plot_scalar"
                entity: "/metrics/tracker/features_count/all"
                options:
                  label: "all_features"
                  color: [80, 170, 255]
              - id: "good_features_count"
                module: "plot_scalar"
                entity: "/metrics/tracker/features_count/good"
                options:
                  label: "good_features"
                  color: [80, 220, 120]
              - id: "lost_features_count"
                module: "plot_scalar"
                entity: "/metrics/tracker/features_count/lost"
                options:
                  label: "lost_features"
                  color: [255, 90, 90]

          - name: "Stereo Metrics"
            type: "Container"
            layout: "Horizontal"
            views:
              - name: "stereo_ok"
                type: "TimeSeries"
                origin: "/metrics/tracker/stereo_ok"
                streams:
                  - id: "stereo_ok_count"
                    module: "plot_scalar"
                    entity: "."
                    options:
                      label: "stereo_ok"
                      color: [80, 220, 120]
              - name: "stereo_ratio"
                type: "TimeSeries"
                origin: "/metrics/tracker/stereo_ratio"
                streams:
                  - id: "stereo_ok_ratio"
                    module: "plot_scalar"
                    entity: "."
                    options:
                      label: "stereo_ratio"
                      color: [255, 200, 80]

          - name: "Interframe Parallax"
            type: "TimeSeries"
            origin: "/metrics/tracker/parallax"
            streams:
              - id: "inner_frame_median_disparity"
                module: "plot_scalar"
                entity: "/metrics/tracker/parallax/median"
                options:
                  label: "median"
                  color: [80, 170, 255]
              - id: "inner_frame_p90_disparity"
                module: "plot_scalar"
                entity: "/metrics/tracker/parallax/p90"
                options:
                  label: "p90"
                  color: [255, 200, 80]

          - name: "Zero Velocity Tracker"
            type: "TimeSeries"
            origin: "/metrics/tracker/zupt"
            streams:
              - id: "visual_zero_velocity_state"
                module: "plot_scalar"
                entity: "/metrics/tracker/zupt/visual"
                options:
                  label: "Visual zero velocity"
                  width: 5.0
                  color: [255, 200, 80]
              - id: "zero_velocity_state"
                module: "plot_scalar"
                entity: "/metrics/tracker/zupt/frontend"
                options:
                  label: "FrontEnd zero velocity"
                  width: 5.0
                  color: [80, 170, 255]
