name: dataset_viz
dataset: euroc_mh_01
dataflow:
  template: dataset-viz-dataflow.yml
  build: false
visualization:
  sink: app
run:
  mode: manual
  autostart_after_ready: false
  stop_after_dataset_done: false
  control_transport: http
