name: my_slam_euroc
dataset: euroc_v101
dataflow:
  template: slam-dataflow.yml
  build: false
visualization:
  sink: app
run:
  mode: manual
  autostart_after_ready: false
  stop_after_dataset_done: false
  control_transport: http
