name: quick_vio_euroc
dataset: euroc_mh_01
dataflow: vio-dataflow.yml
visualization:
  sink: file
run:
  mode: batch_fraction
  fraction: 0.05
  autostart_after_ready: true
  stop_after_dataset_done: true
