colors:
  x_axis_default: [255, 60, 60]
  y_axis_default: [60, 255, 160]
  z_axis_default: [30, 210, 255]
  threshold_default: [255, 0, 0]

views:
  - name: "Rectified Left Image"
    type: "Spatial2D"
    origin: "/sensors/cam0/rect/image"
    streams:
      - id: "left_rect"
        module: "image"
        entity: "."
      - id: "active_feat"
        module: "features"
        entity: "/sensors/cam0/rect/image/features"

  - name: "Visual Place Recognition"
    type: "Container"
    layout: "Vertical"
    views:
      - name: ""
        type: "Container"
        layout: "Horizontal"
        views:
          - name: "PGO: Essential Graph"
            type: "Spatial3D"
            origin: "world/estimates/vpr/essential_graph"
            streams:
              - id: "pgo_graph"
                module: "trajectory"
                entity: "."

          - name: "VPR PointCloud"
            type: "Spatial3D"
            origin: "world/estimates/vpr/loop_closure"
            options:
              view_coordinates: "RDF"
            streams:
              - id: "vpr_reference_frame"
                module: "dynamic_transform"
                entity: "world/estimates/vpr/loop_closure/ref_frame"
                options:
                  show_axes: true
              - id: "vpr_query_frame"
                module: "dynamic_transform"
                entity: "world/estimates/vpr/loop_closure/query_frame"
                options:
                  show_axes: true
              - id: "vpr_reference_points"
                module: "pointcloud"
                entity: "world/estimates/vpr/loop_closure/ref_frame/points"
                options:
                  points_size_prop_name: vpr_reference_points_size
              - id: "vpr_query_points"
                module: "pointcloud"
                entity: "world/estimates/vpr/loop_closure/query_frame/points"
                options:
                  points_size_prop_name: vpr_query_points_size

          - name: "VPR Keyframe"
            type: "Spatial2D"
            origin: "/sensors/cam0/vpr/keyframe_image"
            streams:
              - id: "vpr_left_image"
                module: "image"
                entity: "."
              - id: "vpr_features"
                module: "features"
                entity: "/sensors/cam0/vpr/keyframe_image/features"
                options:
                  show_stereo_baseline: False
      - name: "VPR Loop Pair"
        type: "Spatial2D"
        origin: "/sensors/cam0/vpr/loop_closure/image"
        streams:
          - id: "loop_image"
            module: "image"
            entity: "."
            options:
              width_field: "loop_image_width"
              height_field: "loop_image_height"
              channels: 3

  - name: "Local Map"
    type: "Spatial3D"
    origin: "/world/estimates/local_map"
    streams:
      - id: "pnp_pose"
        module: "dynamic_transform"
        entity: "world/estimates/local_map/pnp/base_link"
        options:
          show_axes: true
      - id: "cam0_in_body"
        module: "static_transform"
        entity: "world/estimates/local_map/pnp/base_link/cam0"
        options:
          show_axes: true
      - id: "points"
        module: "pointcloud"
        entity: "world/estimates/local_map/pnp/base_link/cam0/landmarks"
        options:
          points_size_prop_name: points_size
      - id: "pim_pose"
        module: "dynamic_transform"
        entity: "world/estimates/local_map/pim/base_link"
        options:
          show_axes: true
      - id: "cam0_in_body"
        module: "static_transform"
        entity: "world/estimates/local_map/pim/base_link/cam0"
        options:
          show_axes: true
      - id: "points"
        module: "pointcloud"
        entity: "world/estimates/local_map/pim/base_link/cam0/landmarks"
        options:
          points_size_prop_name: points_size
      - id: "optimized_pose"
        module: "dynamic_transform"
        entity: "world/estimates/local_map/factor_graph/base_link"
        options:
          show_axes: true
      - id: "cam0_in_body"
        module: "static_transform"
        entity: "world/estimates/local_map/factor_graph/base_link/cam0"
        options:
          show_axes: true
      - id: "optimized_points"
        module: "pointcloud"
        entity: "world/estimates/local_map/factor_graph/map/landmarks"
        options:
          points_size_prop_name: optimized_points_size

  - name: "IMU Stream"
    type: "Container"
    layout: "Vertical"
    views:
      - name: "Gyro Stream"
        type: "TimeSeries"
        origin: "/sensors/imu/gyro"
        streams:
          - id: "gyro"
            module: "plot_column"
            entity: "."
            options:
              time_idx: "imu_ts"
              timeline: "sim_time"
              mapping:
                - { index: 0, label: "gyro_x", color: [255, 60, 60] }
                - { index: 1, label: "gyro_y", color: [60, 255, 160] }
                - { index: 2, label: "gyro_z", color: [30, 210, 255] }

      - name: "Accel Stream"
        type: "TimeSeries"
        origin: "/sensors/imu/accel"
        streams:
          - id: "accel"
            module: "plot_column"
            entity: "."
            options:
              time_idx: "imu_ts"
              timeline: "sim_time"
              mapping:
                - { index: 0, label: "accel_x", color: [255, 60, 60] }
                - { index: 1, label: "accel_y", color: [60, 255, 160] }
                - { index: 2, label: "accel_z", color: [30, 210, 255] }

  - name: "Factor-Graph Metrics"
    type: "Container"
    layout: "Vertical"
    views:
      - name: "Optimizator Avg. Post-Fit Error"
        type: "TimeSeries"
        origin: "/metrics/factor_graph/error/post_fit"
        streams:
          - id: "optimizer_post_fit_error"
            module: "plot_scalar"
            entity: "."
            options:
              label: "Post-Fit Error"

      - name: "Gyro Bias"
        type: "TimeSeries"
        origin: "/estimates/gyro_bias/factor_graph"
        streams:
          - id: "optimized_gyro_bias"
            module: "plot_3d_vector"
            entity: "."
      - name: "Accel Bias"
        type: "TimeSeries"
        origin: "/estimates/accel_bias/factor_graph"
        streams:
          - id: "optimized_accel_bias"
            module: "plot_3d_vector"
            entity: "."

      - name: "Prediction Mode"
        type: "TimeSeries"
        origin: "/metrics/factor_graph/prediction_mode"
        streams:
          - id: "prediction_mode"
            module: "plot_scalar"
            entity: "."
            options:
              label: "1=PNP, 2=RAMP, 3=PIM"
              width: 5.0

  - name: "Front-End Metrics"
    type: "Container"
    layout: "Horizontal"
    views:
      - name: "Keyframe Selector Metrics"
        type: "Container"
        layout: "Vertical"
        views:
          - name: "keyframe_dt"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_dt"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_dt/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff"
                  label: "keyframe_time_diff"
                  width: 2.0
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_dt/min_threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff_min_threshold"
                  label: "min_threshold"
                  color: [255, 0, 0]
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "metrics/keyframe_selector/keyframe_dt/max_threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_time_diff_max_threshold"
                  label: "max_threshold"
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false

          - name: "keyframe_connectivity"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_connectivity"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_connectivity/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_connectivity_ratio"
                  label: "keyframe_connectivity"
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_connectivity/threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_connectivity_ratio_threshold"
                  label: "threshold"
                  width: 1.0
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false

          - name: "keyframe_parallax"
            type: "TimeSeries"
            origin: "/metrics/keyframe_selector/keyframe_parallax"
            streams:
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_parallax/value"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_median_parallax"
                  label: "keyframe_parallax"
              - id: "keyframe_metrics"
                module: "plot_scalar"
                entity: "/metrics/keyframe_selector/keyframe_parallax/threshold"
                options:
                  arrow_type: "RecordBatch"
                  arrow_field: "keyframe_median_parallax_threshold"
                  label: "threshold"
                  color: [255, 0, 0]
            options:
              plot_legend:
                visible: false
      - name: "Feature Tracker Metrics"
        type: "Container"
        layout: "Vertical"
        views:
          - name: "Features Count"
            type: "TimeSeries"
            origin: "/metrics/tracker/features_count"
            streams:
              - id: "features_count"
                module: "plot_scalar"
                entity: "."
                options:
                  label: "features_count"

          - name: "Innertframe Parallax"
            type: "TimeSeries"
            origin: "/metrics/tracker/parallax"
            streams:
              - id: "inner_frame_median_disparity"
                module: "plot_scalar"
                entity: "."
                options:
                  label: "t/t+1 parallax"

          - name: "Zero Velocity Tracker"
            type: "TimeSeries"
            origin: "/metrics/tracker/zupt"
            streams:
              - id: "zero_velocity_state"
                module: "plot_scalar"
                entity: "."
                options:
                  label: "(1=ZERO_VELOCITY,0=NON_ZERO_VELOCITY)"
                  width: 5.0

  - name: "Velocity Metrics"
    type: "Container"
    layout: "Vertical"
    views:
      - name: "PIM velocity"
        type: "TimeSeries"
        origin: "/estimates/velocity/pim"
        streams:
          - id: "pim_velocity"
            module: "plot_3d_vector"
            entity: "."
      - name: "PNP velocity"
        type: "TimeSeries"
        origin: "/estimates/velocity/pnp"
        streams:
          - id: "pnp_velocity"
            module: "plot_3d_vector"
            entity: "."
      - name: "Factor Graph Velocity"
        type: "TimeSeries"
        origin: "/estimates/velocity/factor_graph"
        streams:
          - id: "optimized_velocity"
            module: "plot_3d_vector"
            entity: "."
