name: Master/Trunk

on:
  push:
    branches:
      - master

jobs:
  build_wheels:
    name: Build Wheels
    uses: ./.github/workflows/build_wheels.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    needs: build_wheels

  smoke-dataflows:
    name: Smoke Dataflows
    uses: ./.github/workflows/smoke-dataflows.yaml
    needs: test
